Add application/facts sub-resource.
konveyor/tackle2-hub pull request #211
Opened 2023-01-30 21:09 UTC by jortel

Support more granular and atomic API for managing application _facts_.

Added:
- GET /applications/facts
- GET /applications/facts/_key_.
- POST /applications/facts/_key_.
- PUT /applications/facts/_key_.  (created as needed)
- DELETE  /applications/facts/_key_.

Go binding.

- Applications.Facts()
  - List()
  - Get()
  - Create()
  - Set()  (created as needed)
  - Delete

2023-02-10 17:30 UTC, mansam commented on api/application.go
> +			h.reportError(ctx, result.Error)
Needs to `return` after `h.reportError`

2023-02-10 17:37 UTC, mansam requested changes
LGTM except for two small things.

2023-02-10 19:13 UTC, jortel commented on api/application.go
> +	// Facts
Yes.  I added them to roles.

2023-02-10 19:57 UTC, jortel commented on api/application.go
> +	// Facts
Ah.  right, I missed the 
```
	// Facts
	routeGroup = e.Group("/")
	routeGroup.Use(auth.Required("applications.facts"))
```
Fixed.

2023-02-14 17:23 UTC, mansam approved these changes
LGTM

2023-02-14 17:53 UTC, merged